![Bismillah.png](../Images/Bismillah.png)

# NumPy Arrays

- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy stands for Numerical Python.

## Use of NumPy
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with **ndarray** very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

## NumPy is Faster Than Lists
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

Once NumPy is installed, import it in your applications by adding the import keyword:

In [1]:
import numpy as np
print(np.__version__)

1.20.3


## Crearing an array in Numpy

NumPy is used to work with arrays. The array object in NumPy is called <b>ndarray</b>.
We can create a NumPy ndarray object by using the array() function. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Arrays
### 0-D Array
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [3]:
a = np.array(1)
print(a)
print(type(a))

1
<class 'numpy.ndarray'>


### 1-D Array

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 2-D Array

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


### 3-D Array

In [6]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#check dimension
a.ndim

3

### Higher Dimension Array

Lets create an arry with desired dimensions:

In [8]:
a = np.array([1, 2, 3, 4], ndmin=5)
print(a)
print('number of dimensions :', a.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

## Indexing
Array indexing is the same as accessing an array element.

a = np.array([1, 2, 3, 4])

print(a[0])

In [9]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', a[1, 4])

5th element on 2nd dim:  10


In [10]:
#Negative Indexing
print('Last element from 2nd dim: ', a[1, -1])

Last element from 2nd dim:  10


## Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

<b>Note</b>: The result includes the start index, but excludes the end index.

In [11]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[1:5]) #1 to 4th index

[2 3 4 5]


In [12]:
print(a[4:]) #4 to end

[5 6 7]


In [13]:
print(a[:4]) #start to 3rd

[1 2 3 4]


### Step in slicing
Use the step value to determine the step of the slicing:

In [14]:
print(a[1:5:2]) #skip every 2nd element

[2 4]


Return every other element from the entire array:

In [15]:
print(a[::2]) #skip 2nd from start to end

[1 3 5 7]


For 2D arrays

In [16]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [17]:
print(a.dtype)

int32


In [18]:
a = np.array(['apple', 'banana', 'cherry'])

print(a.dtype) #unicode string

<U6


We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [19]:
a = np.array([1, 2, 3, 4], dtype='S')

print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Changing Arrays dtypes
Lets see an example for changing integer to boolean:

In [20]:
a = np.array([0,1,2,3,0])
new = a.astype(bool)

print(new)
print(new.dtype)

[False  True  True  True False]
bool


# Array Maths

## Basic mathematical functions operate elementwise on arrays

In [21]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

Elemetwise sum

In [22]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


Elemetwise difference

In [23]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


Elemetwise multiplication

In [24]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [25]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
